# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9202de0a7f0f833f3ca28930c0b974f2c2ecf2bde723973b56aef5deebd6d54f2230816e009ebcaddef543a0b5d68acd8b1cf7e16a19f21f532c25630ed28971

test:
  secret_key_base: e0cdd15803463161a37e21a9bd559550280f255823d36393bc7af8e1368eced744438a12a4085258d03170f4d0134f161999f0d07d3e1c098c850b0bc6aa0a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
